### ISSUE TITLE
C API for vendor drivers

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapySDR#12]
Currently we offer a C++ and C API for platforms, but only a C++ API for vendor drivers. A C only vendor driver would probably consist of the following:

A definition for a struct of function pointers, each function pointer corresponds to a method of the Device class:

```
typedef struct 
{
    typedefForSetFreq setFreq;
   ....
} SoapySDRDeviceCFunctions;
```

A vendor module would supply a function that returns one of these device structures:

```
EXPORT_API SoapySDRDeviceCFunctions getDeviceFunctions(void)
{
    SoapySDRDeviceCFunctions myDevice;
    myDevice.setFreq = &myDriverSetFreqFunction;
   ...
    return myDevice;
}
```

The SoapySDR implementation would look for the getDeviceFunctions symbol in each module, and make a device object available by the usual means.

**Comment by ncorgan** [comment]
WIP: https://github.com/pothosware/SoapySDR/tree/wip/vendor-c-api

**Comment by ncorgan** [comment]
The current registry implementation makes this difficult when using the common bridge from getDeviceFunctions() to the registry.

https://github.com/pothosware/SoapySDR/blob/b3b93851eb58f07209c725b9fb85dd55c1829bc8/include/SoapySDR/Registry.hpp#L26

The find and make functions are defined as static function pointers, which has been fine for the Soapy modules made so far, but if we're generating per-C-driver find and make functions to add to the registry, we need to be able to call the C driver's find and make functions from within the function passed into the Soapy registry. See the prototype below:

https://github.com/pothosware/SoapySDR/blob/176542b0bd779f33afd5450e38f09f10748d3a80/lib/DeviceCVendorAPI.cpp#L50

Ideally, the implementation for this would be to pass in this function, with the relevant `SoapySDRDeviceCFunctions` struct stored somewhere static and bound to the function. This would be fine if the registry stored std::functions instead of raw function pointers.

In theory, this could be done by keeping the same Registry constructor that takes in a function pointer, adding another constructor that takes in the std::function, and storing them internally as std::functions. Unfortunately, the registry also exposes a function to return this map of function pointers.

https://github.com/pothosware/SoapySDR/blob/b41fa2c6725c332acb1fa2e8703634f30f37331d/include/SoapySDR/Registry.hpp#L60

This would be more than an ABI change. Any thoughts on approaching this?

**Comment by ncorgan** [comment]
@guruofquality bump

**Comment by ncorgan** [comment]
At this point, it's an interesting thought exercise, but it also might not be worth it at this point, so far in. C APIs have already been registered with the C++ API.

**Comment by guruofquality** [comment]
I think this was just an early on wish list, but I dont think there is a strong interest, in fact device drivers would probably just be harder to do in C. The C API for the client side was a must have though.

And if I really had to, I would probably just make a C++ driver module that enables this. It would take this driver struct with all of the function pointers for the user's driver and just dispatch calling into them from yet another C++ overloaded Device class, and same for the find function. So its C++ under the hood, which SoapySDR already is anyway.

**Comment by ncorgan** [comment]
Given this, let's close this, and I'll delete the open branch.
