### ISSUE TITLE
Conversion to/from Float Outside Range

### ISSUE THREAD

**Issue by dwd-pete** [pothosware/SoapySDR#181]
In ConverterPrimatives.hpp, the conversions for an integer type to/from a float use the maximum value of the integer type as the scaling value to get the float to end up between -1.0 and 1.0.

The problem is that integer types have one more number below zero than above zero. For example, `int16_t` has a range of -32768 to 32767. If we divide by 32767 to get the float value, this can be less than -1.0 in the rare case that the sample is right at -32768.

To be fair, I have this exact same bug in some of my code as well and am struggling with how to deal with it. Here are some possible options, all of which have their own issues/merits. Note that I am using an example of converting 16-bit integers to floats, but the same concepts/issues exist for all integer types and also in the opposite direction (i.e., converting from float to integers).

```
// Attempt #1: Use a different scaling value if we're above or below zero. This is probably
// the most correct way of dealing with this since each value for the integer will get a
// unique floating point value. However, we now have to check each sample for whether
// or not it's positive.
inline float S16toF32(int16_t from) {
  if (from < 0) return float(from) / U16_ZERO_OFFSET;
  return float(from) / S16_FULL_SCALE;
} 

// Attempt #2: Check for the rare case of -32768 and assign it to -1.0. Here you still have
// a new conditional statement, but now -1.0 is ambiguous, since it could mean -32767 or
// -32768.
inline float S16toF32(int16_t from) {
  if (from == INT16_MIN) return -1.0;
  return float(from) / S16_FULL_SCALE;
}

// Attempt #3: Don't care about ever hitting the max value. Here, just use 32768 as the
// scaling factor and accept the fact that you will never reach 1.0. The good news is that
// here each integer value has a unique float value and we don't have any conditional
// statements.
inline float S16toF32(int16_t from) {
  return float(from) / U16_ZERO_OFFSET;
} 
```
On a related note, I noticed that the default implementation of `getNativeStreamFormat()` in Device.cpp sets `fullScale` to 32768 and not 32767. Is this a bug or is my understanding of `fullScale` incorrect? There are other modules that use `SOAPY_SDR_CS16` as their native format, but set `fullScale` to 32767 (SoapyUHD also uses 32768 as `fullScale`).

**Comment by coburnw** [comment]
I struggled with this very problem and did a fair amount of research of others code.  As you found, while a float might be symmetrical, ints are not, and using unsigned_zero_offset -1 as the constant seemed to be immune to overflow problems.  But then maybe there are some test patterns i missed.  I certainly hope not.  

The problem is that it needs to work both ways without overflow: 
**when**
k=32767

StoF
32767 / k = 1.0
-32768 / k = - 1.00003

FtoS
1.0 * k = 32767
-1.0 * k = -32767
and
-1.00003 * k = -32768

**whereas**
k=32768

StoF
32767 / k = 0.99996
-32768 / k = 1.0

FtoS
0.99996 * k = 32767
-1.0 * k = -32768
but
1.0 * k = 32768 (overflow)

The single missing code was acceptable in my case and i chose to ignore it.  Additionally I seem to lean towards lower end hardware and didnt want to complicate the calculation.  Perhaps that was the wrong viewpoint.  

Adding/subtracting 1/2 lsb to the float buffer resulting in a 0.999 to -0.999 range is another possibility.  Mathematically that might make more sense, but results in every zero crossing offset by 1/2 lsb which may create problems for others, as may double or missing (in your case) codes.  Im not really sure there is a good answer to the problem.  Have you tried a block that adjusts by 1/2 lsb?

**Comment by dwd-pete** [comment]
I totally didn't catch starting with a CF32 buffer (where 1.0 is a valid input) and using 32768. That will overflow, as you said.

I played around with things a bit today. Approach 1 from above (using two different scalars) is REALLY bad. My theory is that the compiler (I'm using GCC) can't optimize to use SIMD instructions and you end up taking an order of magnitude longer in the loop.

I haven't tried the 1/2 LSB approach yet, but I did take a look at some other projects in an effort to see if there's some known way of doing these types of conversions. I found that GNU Radio blocks simply take in a scalar and pass the problem to the caller. UHD does something similar, but I did find unit test code that used 32767 as the scalar when doing conversions.

I will be working with this more this weekend and will probably poke the GNU Radio mailing list to see if anyone over there has some thoughts. To echo your point, I don't think there's a really good/clean solution here.

**Comment by dwd-pete** [comment]
More discussion here: https://lists.gnu.org/archive/html/discuss-gnuradio/2018-08/msg00126.html

My thoughts are that for CS16->CF32 the best we can do is probably to just divide by 32,768. This will ensure that the resulting CF32 stream will end up in the range of -1.0 to +1.0.

For CF32->CS16 we have two options:
1. Multiply by 32,767, which means you won't ever hit the minimum value of -32,768. This is probably OK for most applications since the original data was symmetrical around zero, and by multiplying by 32,767 we now have a representation of the data that is also symmetrical around zero. Note that this also means that if someone started with a CS16 stream, converted it to CF32, and now wants to go back to CS16 (i.e., they want to get their original data back), they probably want to write their own converter (or to specify an appropriate scale value) to use 32,768 instead.
2. Multiply by 32,768, which will cause an overflow if the stream ever contained a sample of +1.0. If this is performed as saturation arithmetic (as in the case of SIMD instructions) you will end up with the expected value of 32,767. However, the conversion functions in ConverterPrimatives.hpp just do regular math operations, so you are at the mercy of the compiler to select an instruction that performs saturation arithmetic (since the functions are inlined and called from a loop you may get lucky here).

In terms of the SoapySDR codebase, my thoughts are that we have two options moving forward:
1. Edit the functions that convert from integer types to floats to use the zero offset (e.g., 32,768 for short/int16_t).
2. Eliminate any scaling in ConverterPrimatives.hpp. The code that calls these functions in DefaultConverters.cpp already has a scalar passed in, so in effect you would be requiring the caller to scale their samples how they see fit.

I don't have a strong opinion either way, but do think this needs to be changed, since there is a case where a conversion from an integer type to a float will result in the converted value being outside the expected range for floats.

**Comment by coburnw** [comment]
To be clear, you are seeing behavior from Soapy's generic converter that is unexpected (-1.00003 rather than -1.0) rather than erroneous (segfault, overflow, etc).  Is that correct?

The goal of the generic converters was reliable, predictable, format conversion with good performance.  I saw them primarily as a convenience for the device driver developer.  The goal of the ConverterRegistry was to allow the generic Soapy converters to be easily amended for all those times when generic isn't enough.  I think that is where you are now.

If you are working at the application level such as Pothos, you might request the buffers in the raw format and apply your own scaling factors or saturation logic in a block to float convert with the range you expect.  To remove the factors from the generic converters would likely break others existing code.

On the other hand, if you are working at the Soapy level, Soapy's ConverterRegistry allows the driver or application to add custom converters to Soapy's list of supported converters.  The custom converters can either perfectly emulate one of the simple generic converters while using, say, simd optimized algorithms, or can try to cover new ground or formats.  See ConverterRegistry.hpp and DefaultConverters.cpp.  

Its been quite a while since i had my head inside the hood, but i would be willing to attempt a gist if you want to explore the ConverterRegistry at the Soapy level.

**Comment by dwd-pete** [comment]
I think the ability to make a custom converter may be useful in some cases, but in most cases there should be no need for custom converters. That is, with the appropriate compilation flags, GCC (I can't speak for other compilers, since I am a GCC fanboy) spits out SIMD instructions for the generic converters (at least it does just fine on the ARM machine that will run the SoapySDR module I am writing, but I haven't tried it on various flavors of x86 or other architectures). Ultimately my point here is a philosophical one that the generic converters should be "generic" enough for the vast majority of use cases. Converting between CS16 and CF32 shouldn't require me to write my own converter.

That said, I do have a function template that I wrote that takes two buffers of arbitrary types, converts them, and applies a scalar that is passed in from the caller. I haven't tested for converting between different integer types (say int16_t to/from int8_t) but it seems to work just fine converting between CF32 and CS16 (which is my goal since my hardware is 16-bit, but some frameworks like GNU Radio prefer/support 32-bit floats). Also, because GCC is awesome, I get better throughput for my conversions than VOLK can give me, and that library uses specific intrinsics based on what architecture it detects.

My previous point leads to a related discussion on what I've seen in the ConverterRegistry, where I'm guessing it prefers converters based on whether or not I call them "vectorized". This can lead to a less performing converter being chosen simply because someone wrote the code using SIMD intrinsics (and called the converter "vectorized") and didn't trust the compiler to apply similar/better optimizations on its own (i.e., the "generic" converter could be better optimized than the "vectorized" one as I've seen in my own benchmarking vs. VOLK).

Speaking of the ConverterRegistry... I'm new to SoapySDR, so I'm not sure what registering my converter buys me. Can't I just use my converter internally in my SoapySDR module when I detect that the requested type of a stream is not my native type?

In terms of the issue at hand, there is a bug here. If the goal is to make the resulting float between -1.0 and +1.0 (i.e., if the goal was to do what the commit statement said the code does), then the code is currently incorrect and should be fixed (nothing explodes when I do this conversion, but the value is incorrect). Any integer conversion where the integer to be converted is the minimum value for the type will result in a float less than -1.0. For example, I have a 16-bit ADC, so -32,768 is a valid input. This is why I wrote up this issue.

**Comment by coburnw** [comment]
These are the methods i gave consideration to in float to integer conversion, im sure there are several more that either didn't occur to me or i didn't happen across in my search of others work.  I post them here for posterity/blame.  Each is terribly flawed in its own way and every one of them is an argument.  

My criteria in selection of the best of the bunch was reliable, predictable, and complementary.  That is with little risk of crashing, consistent understandable results, and the ability to back feed the result into the mating converter returning the original value as best as possible. 

f = int/k
int = f * k

**Method A:**
    k = 32767

    int > float
     32767   > 1.0
     0       > 0.0
    -32767   > -1.0
    -32768   > -1.00003

    float > int
     1.0     > 32767
     0.0     > 0
    -1.0     > -32767
    -1.00003 > -32768

**Method B:**  fails reliable
     k = 32768

    int > float
     32767  > 0.99997
     0      > 0.0
    -32768  > 1.0

    float > int
     1.0      >  32768 (overflow)
     0.99997  >  32767
     0.0      > 0
    -1.0      > -32768

**Method C:**  fails predictable
k = 32767 for int > 0
k = 32768 for int < 0
When measuring a given p-p value the result changes depending on offset.

**Method D:** fails predictable and complementary
k = 32768 for int to float 
k = 32767 for float to int

32767 > 0.99997 > 32766
int to float to int creates a moving value. 

**Method E:**
k = 32768
offset = 1/(65536) = 15.3 uUnits or 1/2 count
float = int/k + offset
int = (float - offset) * k

     32767 > 0.999985
     0     > 0.0000153
    -32768 > -0.999985

     1.0 > 32767.5 (overflow?)
     0.0 > 1/2 count (rounds to where?)
    -1.0 > -32767.5


What i find humorous is that we are quibbling about one count.  But if it wasn't important, we would have chose a twelve (or eight) bit converter, right?.  The root problem stems from the natural human desire to force an even number of possible combinations into a symmetrical +/- 1 range and demand there be a zero perfectly centered in the middle.

The perfect solution simply hasn't presented itself to me so i chose Method A.  I would be open to a better idea that still adhered to the criteria with the addition of back compatibility.  Perhaps Method E deserves some more investigation.

**Comment by dwd-pete** [comment]
Thanks for summarizing all the different approaches. I think it helps to have everything laid out. My vote would be (in order of preference and/or ease of implementation):

1. Method D, but note that here it would probably make sense to just have the caller select their own scalar. As you pointed out, converting to/from data types doesn't give you the original value back, so you should probably just leave it up to the caller to pick the scalar based on their needs. For example, if I have a CF32 stream that I converted from a CS16 stream (by dividing by 32,768), and I now want to get my original data back, I want to multiply by 32,768. However, if I started with CF32 data (and there's a chance that a value of +1.0 is present), I want to multiply by 32,767 since the resulting data will now also be symmetrical around zero (like the original data) and this will also prevent overflows. My point here is that there are different cases for using a different scalar for the same conversion, which I think is why GNU Radio's conversion blocks just leave the scalar up to the caller.
2. Method B, with saturation arithmetic. In this case the overflows would (predictably) just return the maximum or minimum value. We probably want saturation arithmetic regardless in case someone passes in a comically large scalar to the generic converters (that way we have predictable/expected results). Good examples of saturation arithmetic can be found here: https://github.com/gnuradio/volk/blob/master/include/volk/saturation_arithmetic.h

I will also say that Method A (i.e., not changing the code) is also probably fine, but I can't speak to the application-level issues and potential errors of having a float less than -1.0 (i.e., I'm not sure how strongly the range of -1.0 to +1.0 is actually enforced).

**Comment by guruofquality** [comment]
I guess I will chime in here.

* The converter registry stores converters between source and target formats specified by strings. So these strings do not have to be the default format types. In fact I intend to add a few for packing/unpacking interleaved channels. Example many of the MIMO devices with two channels, new bladerf API.

* The scale factor is a part of the converter API functions so converters can implement arbitrary scaling, scaling can be done in the same loop that does the actual conversion. SIMD implementations can even load the scalar into the appropriate register before the loop. And then of course, certain drivers can change the scale factor based on user streamArgs or hardware requirements, etc. 

* Its annoying that floating point numbers are symmetric around 0, but twos compliment integers are slightly negatively biased. But I don't like the idea of trying to adjust for this, either with an extra addition, or conditional statement based on the sign (extra branching). People are more likely to complain about the potential performance hit anyway.

* I don't think in practice the float to/from int scale factor being a power of two or a power of two minus one really matters. Numbers anywhere near 1.0 full-scale are basically going to be clipping in the hardware.  But I understand how this can be annoying in a unit test. And it is desirable to be able to reverse the conversion.

* 1.0 being full-scale for floating point is probably a good default, even if its not strictly necessary. Its just come to be expected by most applications. And its not like its unprecedented either, ex GPU expressing colors where white is 1.0, 1.0, 1.0

* The only practical issue I think that we could do something about is making the scale factors every where follow a consistent rule of `2^n` or `2^n-1` I'm having trouble caring which one. But I think `2^n` has a few advantages

  * We can write it as a simple shift and potentially implement it easier in hardware (if you had to do floating point offload in an FPGA for example, its just an addition to the exponent).

  * Fixed point numbers/arithmetic can't represent 1.0 (-1.0 yes but not 1.0), so translating that to float. Maybe its just fine that we cant represent positive full scale. The hardware can't do it anyway.

  * So a power of two scale gives us a 1:1 correspondence between the numbers in the integer fixed point and the numbers represented in the floating point.

  * Its possible to work with full-scale 1.0 floats and have numbers that will directly match what the IOs on the ADC/DAC will be.

IMHO - `2^n FTW` - I would rather loose +1.0 in the floating point domain to match up with fixed point arithmetic. And not have to worry about the compressed scaling caused by `2^n-1`. And I would make the other drivers use `2^n` scaling if they already dont. But like I said, its not that big of a deal. But feel free to change my mind. :-)

**Comment by coburnw** [comment]
I updated ConverterPrimatives.hpp in https://github.com/coburnw/SoapySDR/tree/convert_float to use 2^n as scale factors for the signed<>float converters.  This change aligns the operation of the signed<>float converters with the unsigned<>float converters.  Im not sure why that discontinuity didnt bother me before.

While we are here, is it wise to fix the spelling of ConverterPrimatives?  it seems to be refered to only by DefaultConverters, but i have no way to know if others are refering to it also.

If we are on the right track then a merge request.

**Comment by guruofquality** [comment]
> is it wise to fix the spelling of ConverterPrimatives

Like primates as in monkeys? :-)

Yes please, it shouldn't hurt anything.
