### ISSUE TITLE
[Feature Request] Pre-build for aarch64 on conda forge

### ISSUE THREAD

**Issue by eldaromer** [pothosware/SoapySDR#289]
I do a lot of work on embedded devices and have recently been doing research with SDR and signal processing using the Jetson Nano. As part of setup I use conda to install libraries form RapidsAI. The problem is, there is no available build for SoapySDR in the aarch64 conda-forge channel, and installing it from source into a conda environment is proving to be quite hard. 

I would really appreciate, and I'm sure other would as well, if your team added an aarch64 build into conda-forge.

Thank you

**Comment by ryanvolz** [comment]
Hi @eldaromer. You should close this issue and re-file over at https://github.com/conda-forge/soapysdr-feedstock since the SoapySDR folks don't do the conda packaging. (That's me, and I just happened to stumble across this through an unrelated google search.) The short answer is that it takes a little extra effort to do aarch64 packages, and I don't personally have a use for them, so barring a user request I wasn't going to bother. But now you're requesting it, so I can look into it.

**Comment by guruofquality** [comment]
Thanks!
