### ISSUE TITLE
our own hardware 

### ISSUE THREAD

**Issue by nome321** [pothosware/SoapySDR#385]
Hello
I am newbie in SoapySDR world 
I am going to implant SoapySDR on our own hardware Nios processor running 
like 
FPGA =  Intel Altera Arria ii gx 
DAC  = AD9148  two channels
ADC =                  two channels 
CONNECTIVITY SFP+
is it possible can we run SoapySDR on our hardware ?
please helping us 

Thanks

**Comment by zuckschwerdt** [comment]
> can we run SoapySDR **on** our hardware?

Do you really mean on the Nios? (`Nios -> Soapy -> SFP+ -> Ether/IP? -> GUI software`)
SoapySDR is not a protocol as such, so that would be SoapyRemote then?

I assume you mean "**with** our hardware", right? (`Nios -> SFP+ -> Ether/IP? -> Soapy -> GUI software`)
SFP+ is serious power, very nice. Would the data stream be Ethernet / IP / UDP / TCP?
It shouldn't be too complicated to code a Soapy-module to support your protocol. Do you have any further info on the intended protocol?

**Comment by nome321** [comment]
Hello
Thanks for your reply

I assume you mean "with our hardware", right? (Nios -> SFP+ -> Ether/IP? -> Soapy -> GUI software)

Yes This is our Real case 

let me check SoapyRemote if any issue we will face I will share here

Thanks 

Nome

**Comment by zuckschwerdt** [comment]
> > I assume you mean "with our hardware", right? (Nios -> SFP+ -> Ether/IP? -> Soapy -> GUI software)

> Yes This is our Real case

That would not be SoapyRemote then. If you have info on your protocol (`SFP+ -> Protocol? -> Soapy`) let us know.
