### ISSUE TITLE
don't work without sudo 

### ISSUE THREAD

**Issue by Elur12** [pothosware/SoapySDR#416]
When I build SoapySDR in my Radxa Rock4B(Ubuntu 20.04). I encountered a problem that without sudo the program doesn't see the devices, but with sudo it does.

**Comment by fventuri** [comment]
@Elur12 - it might be a problem with missing (or not correctly specified) udev rules.

I am sorry I can't be more specific, but without knowing what kind of devices you have there, it is hard to send you more detailed info, since different types of devices have different udev rules (if you Google 'udev rules' followed by the type of device you have, it should be easy to find out what they should look like).

Franco
